-- =============================================================================
-- Migration: 001_create_conversation_state.sql
-- Phase:     2B2B2 -- Create and Verify the Lakebase Conversation-State Schema
-- Project:   TransparencE Genie State Persistence
-- Branch:    feature/genie-state-persistence
-- Database:  databricks_postgres
-- Endpoint:  projects/transparence-sessions/branches/production/endpoints/primary
-- Date:      2026-07-18
--
-- Purpose:
--   Creates the transparence_state schema and app_conversation table.
--   Grants the app service-principal role all required DML privileges.
--
-- Platform constraints discovered during execution:
--   Databricks Lakebase completely locks app SP roles from interactive users:
--   (1) ALTER SCHEMA/TABLE OWNER TO "SP" requires SET ROLE ability on the SP.
--       GRANT "SP" TO current_user requires ADMIN OPTION (not present).
--   (2) SET ROLE "databricks_superuser" is blocked by set_option=False.
--   (3) ALTER ROLE "SP" ... SET search_path requires CREATEROLE + ADMIN OPTION.
--   (4) SP authentication is prohibited by phase constraints.
--   All three of OWNER transfer, SET ROLE, and ALTER ROLE are blocked.
--   Resolution per spec ("avoid redundant broad grants unless a verified Postgres
--   permission check proves one is necessary"):
--     - Schema and table are owned by the project owner (lokesh.choraria@te.com).
--     - SP receives minimum USAGE + DML privileges via GRANT.
--     - search_path is NOT set as a role attribute; Phase 2C's connection provider
--       MUST set it at connection time using:
--         psycopg.connect(..., options="-c search_path=transparence_state,public")
--       This replaces the ALTER ROLE ... SET search_path requirement and is
--       compatible with the LakebaseConversationRepository adapter.
--
-- Constraints (never violate):
--   - No DROP / TRUNCATE / DELETE / UPDATE / INSERT statements.
--   - No CREATE DATABASE / CREATE ROLE.
--   - No GRANT to PUBLIC.
--   - No superuser, CREATEDB, CREATEROLE or BYPASSRLS privileges.
--   - No SERIAL columns, generated UUID defaults, triggers, functions or extensions.
--   - No seed rows.
--   - No unrelated schema, table or role is touched.
--
-- Execution:
--   Must be run inside a single explicit transaction.
--   Commit only after all Step-10 verification queries pass.
--   On any failure: ROLLBACK; do not retry partial state.
-- =============================================================================


-- ---------------------------------------------------------------------------
-- 1. Schema
-- ---------------------------------------------------------------------------

CREATE SCHEMA transparence_state;


-- ---------------------------------------------------------------------------
-- 2. Table
-- ---------------------------------------------------------------------------
--
-- Exactly ten columns matching the _COLUMNS tuple in
-- app/services/lakebase_conversation_repository.py:
--
--   (0)  conversation_id
--   (1)  owner_user_id_hash
--   (2)  frontend_conversation_id
--   (3)  genie_conversation_id
--   (4)  last_genie_message_id
--   (5)  status
--   (6)  version
--   (7)  created_at
--   (8)  updated_at
--   (9)  last_active_at
--
-- No DEFAULT expressions: the application supplies all values on INSERT.
-- No SERIAL / generated UUID: conversation IDs are generated by the adapter.

CREATE TABLE transparence_state.app_conversation (

    -- (0) Internal server-assigned UUID; the application generates this value.
    conversation_id             UUID            NOT NULL,

    -- (1) HMAC-SHA256(server secret, X-Forwarded-User).  Never a raw email.
    owner_user_id_hash          TEXT            NOT NULL,

    -- (2) UUID supplied by the React browser client (crypto.randomUUID()).
    frontend_conversation_id    TEXT            NOT NULL,

    -- (3) Genie Space conversation ID.  NULL until first Genie turn completes.
    genie_conversation_id       TEXT            NULL,

    -- (4) Most recent Genie message ID.  NULL until first turn completes.
    last_genie_message_id       TEXT            NULL,

    -- (5) Lifecycle status.  Must match ConversationStatus enum exactly.
    status                      TEXT            NOT NULL,

    -- (6) Optimistic concurrency counter.  Starts at 1; incremented per write.
    version                     INTEGER         NOT NULL,

    -- (7) Row creation time (UTC, immutable after INSERT).
    created_at                  TIMESTAMPTZ     NOT NULL,

    -- (8) Last successful mutation time (UTC).
    updated_at                  TIMESTAMPTZ     NOT NULL,

    -- (9) Last user-activity time (UTC); updated by touch and compare_and_update.
    last_active_at              TIMESTAMPTZ     NOT NULL,

    -- -----------------------------------------------------------------------
    -- Constraints
    -- -----------------------------------------------------------------------

    -- Primary key
    CONSTRAINT pk_app_conversation
        PRIMARY KEY (conversation_id),

    -- Logical uniqueness: one record per (owner, browser session)
    CONSTRAINT uq_app_conversation_owner_frontend
        UNIQUE (owner_user_id_hash, frontend_conversation_id),

    -- Status must be one of the four ConversationStatus enum values (uppercase)
    CONSTRAINT chk_app_conversation_status
        CHECK (status IN ('ACTIVE', 'STALE', 'RESET', 'EXPIRED')),

    -- Version starts at 1 and never goes below it
    CONSTRAINT chk_app_conversation_version
        CHECK (version >= 1),

    -- updated_at must not precede created_at
    CONSTRAINT chk_app_conversation_updated_at
        CHECK (updated_at >= created_at),

    -- last_active_at must not precede created_at
    CONSTRAINT chk_app_conversation_last_active_at
        CHECK (last_active_at >= created_at)

);


-- ---------------------------------------------------------------------------
-- 3. Indexes
-- ---------------------------------------------------------------------------

-- Index 1: Owner + recency -- used by list_for_owner (ORDER BY updated_at DESC)
CREATE INDEX idx_app_conversation_owner_updated
    ON transparence_state.app_conversation (owner_user_id_hash, updated_at DESC);

-- Index 2: Genie conversation lookup -- partial (only non-NULL rows indexed)
CREATE INDEX idx_app_conversation_genie_conv
    ON transparence_state.app_conversation (genie_conversation_id)
    WHERE genie_conversation_id IS NOT NULL;

-- Index 3: TTL / cleanup maintenance -- status + activity time
CREATE INDEX idx_app_conversation_status_last_active
    ON transparence_state.app_conversation (status, last_active_at);


-- ---------------------------------------------------------------------------
-- 4. Grant SP operational privileges
-- ---------------------------------------------------------------------------
--
-- Platform locks prevent OWNER transfer and ALTER ROLE (see header).
-- The SP receives minimum privileges for LakebaseConversationRepository:
--   USAGE on schema  -- enables schema resolution when search_path is set
--                       at connection time in Phase 2C connection provider
--   SELECT, INSERT, UPDATE, DELETE on table  -- full DML surface

GRANT USAGE
    ON SCHEMA transparence_state
    TO "488a0acb-5804-42f0-98b1-a02cc13c4573";

GRANT SELECT, INSERT, UPDATE, DELETE
    ON TABLE transparence_state.app_conversation
    TO "488a0acb-5804-42f0-98b1-a02cc13c4573";


-- ---------------------------------------------------------------------------
-- 5. Restrict PUBLIC access to the new schema
-- ---------------------------------------------------------------------------
--
-- PostgreSQL grants USAGE + CREATE on new schemas to PUBLIC by default.
-- Explicitly revoke both so only the schema owner and the granted SP can access it.

REVOKE CREATE ON SCHEMA transparence_state FROM PUBLIC;
REVOKE USAGE  ON SCHEMA transparence_state FROM PUBLIC;


-- ---------------------------------------------------------------------------
-- NOTE: search_path is NOT set as a role attribute
-- ---------------------------------------------------------------------------
--
-- ALTER ROLE "488a0acb-5804-42f0-98b1-a02cc13c4573"
--     IN DATABASE databricks_postgres
--     SET search_path = transparence_state, public;
--
-- The above is blocked: Lakebase requires CREATEROLE + ADMIN OPTION on the SP
-- role to run ALTER ROLE, which the interactive project owner does not have.
--
-- REQUIRED ACTION for Phase 2C connection provider:
--   Set search_path at connection time so the unqualified reference in
--   LakebaseConversationRepository._TABLE_NAME = "app_conversation" resolves
--   to transparence_state.app_conversation.
--
--   Example (psycopg3):
--     psycopg.connect(
--         host=..., dbname="databricks_postgres", user=..., password=...,
--         sslmode="require",
--         options="-c search_path=transparence_state,public"
--     )
--
--   Or via connection pool creator function, per the Databricks Lakebase
--   connectivity guide.
