-- =============================================================================
-- Migration: 002_create_conversation_message.sql
-- Phase:     H1 -- Owner-Scoped Conversation History Persistence
-- Project:   TransparencE Genie State Persistence
-- Branch:    feature/genie-state-persistence
-- Database:  databricks_postgres
-- Endpoint:  projects/transparence-sessions/branches/production/endpoints/primary
-- Date:      2026-07-21
--
-- Purpose:
--   Creates the app_conversation_message table in the transparence_state schema.
--   Stores owner-scoped message history for browser-refresh rehydration.
--   Persists user prompts and normalized assistant response payloads.
--   Grants the app service-principal role all required DML privileges.
--
-- Platform constraints (inherited from 001_create_conversation_state.sql):
--   - No DEFAULT expressions: application supplies all values on INSERT.
--   - No SERIAL / generated UUID columns.
--   - No triggers, functions or extensions.
--   - search_path must be set at connection time by LakebaseConnectionProvider.
--   - OWNER transfer and ALTER ROLE are blocked for the SP role.
--
-- Security constraints:
--   - response_payload_json must NOT contain owner hashes, Genie IDs, SQL
--     credentials, process-local keys, or raw exception traces.
--   - message_text is capped at 4000 characters (enforced at app level + here).
--   - response_payload_json is capped at 524288 bytes (512 KiB).
--
-- Idempotency:
--   All CREATE statements use IF NOT EXISTS.
--   All GRANT/REVOKE statements are safe to repeat.
--   Schema creation is NOT repeated here (created in 001).
--
-- Execution:
--   Must be run inside a single explicit transaction.
--   Commit only after all Step-11 verification queries pass.
--   On any failure: ROLLBACK; do not retry partial state.
-- =============================================================================


-- ---------------------------------------------------------------------------
-- 1. Table
-- ---------------------------------------------------------------------------
--
-- Columns (positional order must match _MSG_COLUMNS in lakebase_message_repository.py):
--
--   (0)  message_id
--   (1)  owner_user_id_hash
--   (2)  frontend_conversation_id
--   (3)  message_sequence
--   (4)  role
--   (5)  message_text
--   (6)  response_payload_json
--   (7)  is_active
--   (8)  created_at
--   (9)  updated_at
--
-- No DEFAULT expressions: application supplies all values on INSERT.
-- No SERIAL / generated UUID: message_id is generated by the repository.

CREATE TABLE IF NOT EXISTS transparence_state.app_conversation_message (

    -- (0) Application-generated UUID; unique per message.
    message_id                  UUID            NOT NULL,

    -- (1) HMAC-SHA256 of the Databricks user email.
    --     Same derivation as app_conversation.owner_user_id_hash.
    --     Never a raw email or Databricks user ID.
    owner_user_id_hash          TEXT            NOT NULL,

    -- (2) UUID supplied by the React browser client.
    --     Same value as app_conversation.frontend_conversation_id.
    frontend_conversation_id    TEXT            NOT NULL,

    -- (3) 1-based sequence number within (owner, frontend_conversation_id).
    --     Monotonically increasing; drives chronological ordering.
    message_sequence            INTEGER         NOT NULL,

    -- (4) Message author.  Exactly 'user' or 'assistant'.
    role                        TEXT            NOT NULL,

    -- (5) Plain-text content.
    --     For user messages: the prompt as typed.
    --     For assistant messages: the narrative text portion of the response.
    --     Capped at 4000 characters; enforced at the application layer.
    message_text                TEXT            NOT NULL,

    -- (6) JSON-serialised application response payload.
    --     Populated only for 'assistant' messages.  NULL for 'user' messages.
    --     Contains: status, is_table, table_data (bounded rows), row_count,
    --               suggested_questions, computed_chart_data, computed_metrics,
    --               query_description, has_visualization, source.
    --     MUST NOT contain: owner hashes, Genie IDs, process-local keys,
    --               SQL credentials, download keys, export IDs, or raw traces.
    --     Capped at 524288 bytes (512 KiB); enforced at the application layer.
    response_payload_json       TEXT            NULL,

    -- (7) FALSE when the parent conversation was reset, expired, or deleted.
    --     Deactivated messages are excluded from history reads.
    is_active                   BOOLEAN         NOT NULL,

    -- (8) UTC timestamp of this row's creation; immutable after INSERT.
    created_at                  TIMESTAMPTZ     NOT NULL,

    -- (9) UTC timestamp of last update.  Set to created_at on INSERT;
    --     updated when is_active transitions to FALSE.
    updated_at                  TIMESTAMPTZ     NOT NULL,


    -- -----------------------------------------------------------------------
    -- Constraints
    -- -----------------------------------------------------------------------

    -- Primary key
    CONSTRAINT pk_app_conversation_message
        PRIMARY KEY (message_id),

    -- Sequence uniqueness: no two messages in the same conversation may share
    -- the same sequence number.  This is the compare-and-swap guard against
    -- concurrent writes.
    CONSTRAINT uq_conv_msg_sequence
        UNIQUE (owner_user_id_hash, frontend_conversation_id, message_sequence),

    -- Role must be one of the two permitted values.
    CONSTRAINT chk_conv_msg_role
        CHECK (role IN ('user', 'assistant')),

    -- Sequence must be a positive integer.
    CONSTRAINT chk_conv_msg_sequence_positive
        CHECK (message_sequence >= 1),

    -- message_text must not be empty.
    CONSTRAINT chk_conv_msg_text_nonempty
        CHECK (length(message_text) >= 1),

    -- updated_at must not precede created_at.
    CONSTRAINT chk_conv_msg_updated_at
        CHECK (updated_at >= created_at)

);


-- ---------------------------------------------------------------------------
-- 2. Indexes
-- ---------------------------------------------------------------------------

-- Index 1: Primary history read path.
--   Used by list_messages() which orders by (owner, frontend_id, sequence ASC).
--   Partial index on is_active=TRUE avoids scanning deactivated rows.
CREATE INDEX IF NOT EXISTS idx_conv_msg_history_read
    ON transparence_state.app_conversation_message
        (owner_user_id_hash, frontend_conversation_id, message_sequence ASC)
    WHERE is_active = TRUE;

-- Index 2: Deactivation path.
--   Used by deactivate_messages() which updates by (owner, frontend_id).
CREATE INDEX IF NOT EXISTS idx_conv_msg_deactivate
    ON transparence_state.app_conversation_message
        (owner_user_id_hash, frontend_conversation_id)
    WHERE is_active = TRUE;

-- Index 3: Created-at ordering (fallback / chronological audit).
CREATE INDEX IF NOT EXISTS idx_conv_msg_created_at
    ON transparence_state.app_conversation_message
        (frontend_conversation_id, created_at ASC);


-- ---------------------------------------------------------------------------
-- 3. Grant SP operational privileges
-- ---------------------------------------------------------------------------
--
-- Same SP UUID as in 001_create_conversation_state.sql.
-- Schema USAGE was already granted in 001; repeated here is safe (idempotent).

GRANT USAGE
    ON SCHEMA transparence_state
    TO "488a0acb-5804-42f0-98b1-a02cc13c4573";

GRANT SELECT, INSERT, UPDATE, DELETE
    ON TABLE transparence_state.app_conversation_message
    TO "488a0acb-5804-42f0-98b1-a02cc13c4573";


-- ---------------------------------------------------------------------------
-- 4. Restrict PUBLIC access
-- ---------------------------------------------------------------------------

REVOKE ALL ON TABLE transparence_state.app_conversation_message FROM PUBLIC;


-- ---------------------------------------------------------------------------
-- 5. Verification queries (run after COMMIT to confirm correct state)
-- ---------------------------------------------------------------------------
--
-- These are CHECK queries only — they do not modify data.
-- Run each individually after the main transaction commits.
--
-- V1: Table exists with correct column count:
--   SELECT COUNT(*) FROM information_schema.columns
--   WHERE table_schema = 'transparence_state'
--     AND table_name   = 'app_conversation_message';
--   -- Expected: 10
--
-- V2: Primary key constraint present:
--   SELECT constraint_name FROM information_schema.table_constraints
--   WHERE table_schema = 'transparence_state'
--     AND table_name   = 'app_conversation_message'
--     AND constraint_type = 'PRIMARY KEY';
--   -- Expected: pk_app_conversation_message
--
-- V3: Unique sequence constraint present:
--   SELECT constraint_name FROM information_schema.table_constraints
--   WHERE table_schema = 'transparence_state'
--     AND table_name   = 'app_conversation_message'
--     AND constraint_type = 'UNIQUE';
--   -- Expected: uq_conv_msg_sequence
--
-- V4: SP can SELECT (must be run as SP role):
--   SELECT COUNT(*) FROM transparence_state.app_conversation_message;
--   -- Expected: 0 (empty table)
--
-- V5: Index on history read path present:
--   SELECT indexname FROM pg_indexes
--   WHERE schemaname = 'transparence_state'
--     AND tablename  = 'app_conversation_message';
--   -- Expected: 3 indexes listed
-- ---------------------------------------------------------------------------
