"""Core chat pipeline - orchestrates all services.

POST /api/chat endpoint that handles the full lifecycle:
1. Intent classification
2. Business rules preprocessing (BU/country resolution)
3. SQL generation via LLM
4. SQL validation (guardrails)
5. SQL repair if validation fails
6. SQL execution against warehouse
7. Result summarization
8. Conversation persistence
9. Audit logging
10. CSV export (for large results)
"""

import logging
import random
import re
import time
import threading
from typing import Optional

from fastapi import APIRouter, HTTPException, Request
from pydantic import BaseModel

from app.business_rules.mappings import (
    BU_NAME_TO_CODE,
    CUSTOM_FALLBACK_MESSAGE,
    convert_bu_to_code,
    convert_country_to_iso,
    has_query_intent,
    match_detailed_request,
)
from app.business_rules.prompt_builder import build_system_prompt
from app.config import settings
from app.guardrails.sql_validator import SQLValidator
from app.services.audit_service import AuditService
from app.services.conversation_manager import ConversationManager
from app.services.llm_service import Intent, LLMService
from app.services.sql_service import SQLService

# --- Phase 4B2: Trusted request identity runtime (disabled by default) ---
from app.services.request_owner_identity_runtime import (
    REQUEST_OWNER_IDENTITY_STATE_ATTRIBUTE,
    RequestOwnerIdentityRuntimeConfigurationError,
    RequestOwnerIdentityRuntimeResolutionError,
    resolve_request_owner_identity,
)

# --- Phase 4C4B3A: Opaque owner-scoped process-local conversation key ---
from app.services.process_local_conversation_key import (
    build_process_local_conversation_key,
    ProcessLocalConversationKeyError,
)

# --- Phase 7B: New accuracy pipeline (feature-flag controlled) ---
from app.config import settings as _app_settings

logger = logging.getLogger(__name__)
router = APIRouter()


# =============================================================================
# REQUEST / RESPONSE MODELS
# =============================================================================


class ChatRequest(BaseModel):
    """Incoming chat request."""
    message: str
    conversation_id: Optional[str] = None


class TableData(BaseModel):
    """Structured table result."""
    headers: list
    rows: list


class ChatResponse(BaseModel):
    """Standard chat response format."""
    status: str  # success, error, greeting, off_topic, clarification
    message: str
    is_table: bool = False
    table_data: Optional[TableData] = None
    row_count: int = 0
    preview_row_count: int = 0
    returned_row_count: int = 0
    total_row_count: Optional[int] = None
    export_row_count: Optional[int] = None
    display_row_limit: int = 100
    download_key: Optional[str] = None
    export_id: Optional[str] = None
    export_status: Optional[str] = None
    export_mode: Optional[str] = None
    execution_time_ms: int = 0
    conversation_id: Optional[str] = None
    clarification: Optional[str] = None
    # --- Genie extension fields (populated only when USE_GENIE_BACKEND=true) ---
    # Frontend ignores unknown fields; Phase G7 will add UI components for these.
    suggested_questions: Optional[list] = None
    has_visualization: bool = False
    visualization: Optional[dict] = None
    source: Optional[str] = None
    genie_conversation_id: Optional[str] = None   # audit / multi-turn correlation
    fallback_recommended: Optional[bool] = None   # True when Genie deferred to next pipeline
    genie_message_id: Optional[str] = None        # Genie message ID; used for per-turn traceability
    generated_sql: Optional[str] = None           # SQL generated by Genie; displayed in SqlAccordion (G7)
    query_description: Optional[str] = None        # Genie query.description — context line shown in UI (Q2)
    genie_thought_description: Optional[str] = None  # THOUGHT_TYPE_DESCRIPTION from Genie thoughts (Q2)
    computed_chart_data: Optional[dict] = None      # {data, x_key, y_key} from table summarizer (Q3)
    computed_metrics: Optional[dict] = None         # aggregate stats from table summarizer (Q3)


# =============================================================================
# SERVICE INSTANCES (initialized once per worker)
# =============================================================================

_llm: Optional[LLMService] = None
_sql: Optional[SQLService] = None
_validator: Optional[SQLValidator] = None
_conversations: Optional[ConversationManager] = None
_audit: Optional[AuditService] = None


def _get_services():
    """Lazy-init all services."""
    global _llm, _sql, _validator, _conversations, _audit
    if _llm is None:
        _llm = LLMService()
        _sql = SQLService()
        _validator = SQLValidator()
        _conversations = ConversationManager()
        _audit = AuditService()
    return _llm, _sql, _validator, _conversations, _audit


# =============================================================================
# GREETING / OFF-TOPIC RESPONSES
# =============================================================================

_GREETING_RESPONSES = {
    "hello": [
        "Hey there! How can I help you with shipments today?",
        "Hi! Ready to help you track shipments, check delays, or analyze logistics data. What do you need?",
        "Hello! What shipment information can I pull up for you?",
    ],
    "casual": [
        "Hey! I'm here to help with shipment queries. What are you looking for?",
        "What's up! Need to track a shipment or check some logistics data?",
        "Hi there! Ask me about shipments, delays, revenue - I've got you covered.",
    ],
    "thanks": [
        "You're welcome! Need anything else?",
        "Happy to help! Let me know if there's anything else.",
        "Glad I could assist! Any other shipment queries?",
    ],
    "bye": [
        "See you later! Come back anytime.",
        "Bye! Happy to help whenever you need shipment data.",
        "Take care! I'll be here when you need me.",
    ],
}

_OFF_TOPIC_RESPONSES = [
    "I specialize in shipment and logistics data. Try asking about shipment status, delays, revenue, or routes!",
    "That's outside my expertise - I'm built for shipment tracking. Ask me about deliveries, delays, or transport analytics!",
    "I'm focused on logistics intelligence. I can help with shipment lookups, delay analysis, revenue by BU, and more.",
]

# Fast pattern-match for obvious intents (skips LLM call entirely)
_GREETING_PATTERNS = {
    "hello": ("hi", "hello", "hey", "hii", "hiii", "good morning", "good afternoon", "good evening"),
    "casual": ("whats up", "what's up", "sup", "yo", "howdy", "how are you", "how's it going"),
    "thanks": ("thank", "thanks", "thx", "appreciate", "cheers"),
    "bye": ("bye", "goodbye", "see you", "later", "cya", "take care"),
}

# Known greeting prefixes that users commonly put before a real query
_GREETING_PREFIXES = ("hi ", "hey ", "hello ", "yo ", "hii ", "hiii ")

# Export threshold - create CSV if result exceeds this many rows
_EXPORT_THRESHOLD = 20


# =============================================================================
# MAIN CHAT ENDPOINT
# =============================================================================


@router.post("/chat", response_model=ChatResponse)
async def chat(request: Request, body: ChatRequest):
    """Process a natural language query through the full pipeline."""
    start_time = time.time()

    # ── Phase 4B2: Trusted request identity extraction (disabled by default) ─
    # When ENABLE_TRUSTED_REQUEST_OWNER_IDENTITY is false (the default),
    # resolve_request_owner_identity returns None immediately without reading
    # CONVERSATION_OWNER_HMAC_SECRET or inspecting any trusted header.
    # When true, the runtime derives RequestOwnerIdentity from the trusted
    # forwarded-user header and attaches the immutable object to request.state.
    # The identity is not yet used to
    # access durable conversations (Phase 4C).
    try:
        _trusted_identity = resolve_request_owner_identity(headers=request.headers)
    except RequestOwnerIdentityRuntimeConfigurationError:
        raise HTTPException(
            status_code=503,
            detail="Trusted request identity is unavailable.",
        )
    except RequestOwnerIdentityRuntimeResolutionError:
        raise HTTPException(
            status_code=401,
            detail="Trusted request identity is required.",
        )
    if _trusted_identity is not None:
        setattr(request.state, REQUEST_OWNER_IDENTITY_STATE_ATTRIBUTE, _trusted_identity)

    llm, sql_svc, validator, conversations, audit = _get_services()

    user_message = body.message.strip()
    # Prefer X-Forwarded-Email (Databricks Apps) then X-User-Email (local dev)
    user_id = (
        request.headers.get("X-Forwarded-Email")
        or request.headers.get("X-User-Email")
        or "anonymous"
    )

    # ── M1: Determine frontend conversation ID ──────────────────────────────
    # This is the ID the browser supplies (and uses for local UI rendering).
    # It must NOT be used directly as a backend state key.
    frontend_conversation_id = body.conversation_id
    if not frontend_conversation_id:
        frontend_conversation_id = conversations.create_conversation(user_id=user_id)

    # ── M2: Build the namespaced backend conversation key ────────────────────
    # request.state.session_id is set by session_middleware in main.py for
    # every HTTP request via a secure httponly cookie.
    # Prefixing with session_id means two users who both open the app and get
    # frontend_conversation_id="1" will have DIFFERENT GenieSessionStore keys:
    #   User A (cookie aaXXX): server key = "aaXXX:1"
    #   User B (cookie bbYYY): server key = "bbYYY:1"
    # This is the primary P0 multi-user isolation fix.
    session_id = getattr(getattr(request, "state", None), "session_id", None) or "nosession"
    server_conversation_key = f"{session_id}:{frontend_conversation_id}"

    # Store user message under the namespaced key
    conversations.add_message(
        conversation_id=server_conversation_key,
        role="user",
        content=user_message,
    )

    try:
        # =================================================================
        # FEATURE FLAG: Genie Backend (Phase G4/G5)
        # Routing priority:
        #   1. Genie (USE_GENIE_BACKEND=true)
        #   2. New accuracy pipeline (USE_NEW_ACCURACY_PIPELINE=true)
        #   3. Old pipeline (default — both flags false)
        # If Genie fails and GENIE_FALLBACK_TO_CUSTOM_PIPELINE=true,
        # execution falls through to the next enabled pipeline below.
        # =================================================================
        if _app_settings.USE_GENIE_BACKEND:
            try:
                from app.services.genie_backend_factory import (
                    get_genie_pipeline as _get_genie_pipeline,
                )

                # Auth: use the app service-principal via SDK credential chain.
                # NOTE: X-Forwarded-Access-Token is NOT used here because the
                # app's effective_user_api_scopes is IAM-only; the forwarded
                # token cannot call the Genie API.  The SP must be granted
                # CAN USE on the Genie Space (see ops runbook).
                # Broader OAuth scopes can be added in G10 for user-delegated auth.
                _genie_pl  = _get_genie_pipeline(user_token=None)

                # Phase 4C1: Pass trusted owner key into pipeline boundary.
                # When identity is disabled _trusted_identity is None; pass None.
                _owner_key = (
                    _trusted_identity.owner_user_id_hash
                    if _trusted_identity is not None
                    else None
                )

                # Phase 4C4B3A: Owner-scoped opaque process-local key.
                # When trusted identity is enabled, derive an opaque digest from
                # (owner_hash, session_id, frontend_conversation_id) so that two
                # different trusted owners sharing the same session cookie and
                # frontend ID cannot collide in GenieSessionStore.
                # When identity is disabled, preserve the legacy session:frontend
                # key so that existing multi-user cookie isolation is unchanged.
                # The raw frontend_conversation_id is ALWAYS passed separately so
                # the durable repository layer can use it without parsing the key.
                if _trusted_identity is not None:
                    _process_local_key = build_process_local_conversation_key(
                        owner_user_id_hash=_trusted_identity.owner_user_id_hash,
                        session_id=session_id,
                        frontend_conversation_id=frontend_conversation_id,
                    )
                else:
                    _process_local_key = server_conversation_key

                genie_result = _genie_pl.run(
                    user_message=user_message,
                    app_conversation_id=_process_local_key,
                    owner_key=_owner_key,
                    frontend_conversation_id=frontend_conversation_id,
                )

                if not genie_result.get("fallback_recommended", False):
                    # Genie answered successfully
                    conversations.add_message(
                        conversation_id=server_conversation_key,
                        role="assistant",
                        content=genie_result.get("message", ""),
                        intent="genie",
                    )
                    return ChatResponse(
                        status=genie_result.get("status", "success"),
                        message=genie_result.get("message", ""),
                        is_table=genie_result.get("is_table", False),
                        table_data=_genie_table_to_table_data(
                            genie_result.get("table_data")
                        ),
                        row_count=genie_result.get("row_count", 0),
                        preview_row_count=genie_result.get("preview_row_count", 0),
                        returned_row_count=genie_result.get("returned_row_count", 0),
                        total_row_count=genie_result.get("total_row_count"),
                        export_row_count=genie_result.get("export_row_count"),
                        display_row_limit=genie_result.get("display_row_limit", 100),
                        download_key=genie_result.get("download_key"),
                        export_id=genie_result.get("export_id"),
                        export_status=genie_result.get("export_status"),
                        export_mode=genie_result.get("export_mode"),
                        execution_time_ms=genie_result.get(
                            "execution_time_ms", _elapsed_ms(start_time)
                        ),
                        conversation_id=frontend_conversation_id,
                        clarification=genie_result.get("clarification"),
                        suggested_questions=genie_result.get("suggested_questions"),
                        has_visualization=genie_result.get("has_visualization", False),
                        visualization=genie_result.get("visualization"),
                        source=genie_result.get("source", "genie"),
                        genie_conversation_id=genie_result.get("genie_conversation_id"),
                        fallback_recommended=genie_result.get("fallback_recommended", False),
                        genie_message_id=genie_result.get("genie_message_id"),
                        generated_sql=(
                            genie_result.get("generated_sql")
                            if (_app_settings.GENIE_SHOW_SQL or _app_settings.GENIE_DEBUG)
                            else None
                        ),
                        query_description=genie_result.get("query_description"),
                        genie_thought_description=(
                            genie_result.get("genie_thought_description")
                            if _app_settings.GENIE_DEBUG
                            else None
                        ),
                        computed_chart_data=genie_result.get("computed_chart_data"),
                        computed_metrics=genie_result.get("computed_metrics"),
                    )

                # fallback_recommended=True: Genie wants us to try another pipeline
                if not _app_settings.GENIE_FALLBACK_TO_CUSTOM_PIPELINE:
                    # Fallback disabled — surface Genie's error to the user
                    return ChatResponse(
                        status="error",
                        message=genie_result.get(
                            "message",
                            "I wasn't able to complete that request. Please try again.",
                        ),
                        conversation_id=frontend_conversation_id,
                        execution_time_ms=genie_result.get(
                            "execution_time_ms", _elapsed_ms(start_time)
                        ),
                        source="genie",
                    )

                logger.info(
                    "Genie fallback for conv=%s — routing to next pipeline",
                    server_conversation_key,
                )
                # Fall through to USE_NEW_ACCURACY_PIPELINE / old pipeline below

            except ProcessLocalConversationKeyError:
                # Phase 4C4B3A: Key validation failure is always a hard error;
                # never fall through to the custom pipeline fallback.
                logger.error(
                    "Genie backend error for conv=%s: Process-local conversation key input validation failed.",
                    server_conversation_key,
                )
                return ChatResponse(
                    status="error",
                    message="I wasn't able to complete that request. Please try again.",
                    conversation_id=frontend_conversation_id,
                    execution_time_ms=_elapsed_ms(start_time),
                    source="genie",
                    fallback_recommended=False,
                )

            except Exception as _genie_exc:
                _genie_err_str = str(_genie_exc)[:500]
                logger.error(
                    "Genie backend error for conv=%s: %s",
                    server_conversation_key,
                    _genie_err_str,
                )
                if not _app_settings.GENIE_FALLBACK_TO_CUSTOM_PIPELINE:
                    # When GENIE_DEBUG=true, surface the actual error so it can be read in the UI
                    _err_msg = (
                        f"Genie error (debug): {_genie_err_str}"
                        if getattr(_app_settings, "GENIE_DEBUG", False)
                        else "I wasn't able to complete that request. Please try again."
                    )
                    return ChatResponse(
                        status="error",
                        message=_err_msg,
                        conversation_id=frontend_conversation_id,
                        execution_time_ms=_elapsed_ms(start_time),
                        source="genie",
                    )
                # Fall through to next pipeline

        # =================================================================
        # FEATURE FLAG: New Accuracy Pipeline (Phase 7B)
        # =================================================================
        if _app_settings.USE_NEW_ACCURACY_PIPELINE:
            try:
                from app.services.pipeline_adapter import (
                    SQLServiceAdapter,
                    SQLValidatorAdapter,
                    LLMServiceAdapter,
                    generate_export_key,
                    map_pipeline_result_to_response,
                    create_state_manager,
                )
                from app.services.chat_pipeline import ChatPipeline, ChatPipelineInput

                pipeline = ChatPipeline(
                    sql_executor=SQLServiceAdapter(sql_svc),
                    sql_validator=SQLValidatorAdapter(validator),
                    llm_service=LLMServiceAdapter(llm),
                    state_manager=create_state_manager(sql_svc),
                    table_name=settings.SHIPMENT_TABLE_NAME,
                    export_key_generator=generate_export_key,
                )
                pipeline_input = ChatPipelineInput(
                    user_input=user_message,
                    conversation_id=server_conversation_key,
                    debug=_app_settings.NEW_PIPELINE_DEBUG,
                )
                pipeline_result = pipeline.run(pipeline_input)

                # Handle LLM fallback: route to old pipeline if configured
                if (
                    pipeline_result.status == "requires_llm_fallback"
                    and _app_settings.NEW_PIPELINE_FALLBACK_TO_OLD
                ):
                    logger.info("New pipeline requires LLM fallback, routing to old pipeline")
                    pass  # Fall through to old pipeline below
                else:
                    # Map result to frontend contract
                    response_dict = map_pipeline_result_to_response(
                        pipeline_result, frontend_conversation_id, _elapsed_ms(start_time)
                    )
                    # Store assistant response
                    conversations.add_message(
                        conversation_id=server_conversation_key,
                        role="assistant",
                        content=pipeline_result.message,
                        intent=pipeline_result.intent,
                    )
                    return ChatResponse(**response_dict)

            except Exception as e:
                logger.error(
                    "New accuracy pipeline failed: %s", str(e)[:300],
                    exc_info=_app_settings.NEW_PIPELINE_DEBUG,
                )
                if not _app_settings.NEW_PIPELINE_FALLBACK_TO_OLD:
                    return ChatResponse(
                        status="error",
                        message="An error occurred processing your request. Please try again.",
                        conversation_id=frontend_conversation_id,
                        execution_time_ms=_elapsed_ms(start_time),
                    )
                # Fall through to old pipeline

        # =====================================================================
        # STEP 1: Intent Classification (fast path + LLM fallback)
        # =====================================================================
        # Fast pattern-match ONLY for pure greetings (no query content)
        fast_intent = _fast_classify(user_message)
        if fast_intent:
            msg = random.choice(_GREETING_RESPONSES[fast_intent])
            conversations.add_message(
                conversation_id=server_conversation_key, role="assistant",
                content=msg, intent="greeting",
            )
            return ChatResponse(
                status="greeting", message=msg,
                conversation_id=frontend_conversation_id,
                execution_time_ms=_elapsed_ms(start_time),
            )

        # Strip greeting prefix before LLM classification
        # "hi can you give me shipments from Mexico?" → "can you give me shipments from Mexico?"
        cleaned_message = _strip_greeting_prefix(user_message)

        # LLM-based classification for ambiguous messages
        intent_result = llm.classify_intent(cleaned_message)
        intent = intent_result.intent

        # Handle non-query intents
        if intent == Intent.GREETING:
            msg = random.choice(_GREETING_RESPONSES["hello"])
            conversations.add_message(
                conversation_id=server_conversation_key, role="assistant",
                content=msg, intent="greeting",
            )
            return ChatResponse(
                status="greeting", message=msg,
                conversation_id=frontend_conversation_id,
                execution_time_ms=_elapsed_ms(start_time),
            )

        if intent == Intent.OFF_TOPIC:
            msg = random.choice(_OFF_TOPIC_RESPONSES)
            conversations.add_message(
                conversation_id=server_conversation_key, role="assistant",
                content=msg, intent="off_topic",
            )
            return ChatResponse(
                status="off_topic", message=msg,
                conversation_id=frontend_conversation_id,
                execution_time_ms=_elapsed_ms(start_time),
            )

        if intent == Intent.CLARIFICATION_NEEDED:
            clarification_msg = (
                "I'd like to help, but I need a bit more detail. "
                "Could you specify what shipment data you're looking for? "
                "For example: a shipment number, business unit, country, date range, or metric."
            )
            conversations.add_message(
                conversation_id=server_conversation_key, role="assistant",
                content=clarification_msg, intent="clarification_needed",
            )
            return ChatResponse(
                status="clarification", message=clarification_msg,
                conversation_id=frontend_conversation_id,
                clarification=clarification_msg,
                execution_time_ms=_elapsed_ms(start_time),
            )

        # =====================================================================
        # STEP 2: Business Rules Preprocessing
        # =====================================================================
        processed_message = _preprocess_message(cleaned_message)

        # Check for detailed shipment request (regex pattern match)
        detail_shipment_id = match_detailed_request(user_message)

        # =====================================================================
        # STEP 3: SQL Generation
        # =====================================================================
        system_prompt = build_system_prompt(settings.SHIPMENT_TABLE_NAME)

        # Get conversation context for follow-ups
        llm_context = None
        if intent == Intent.FOLLOW_UP:
            llm_context = conversations.get_llm_context(server_conversation_key, max_turns=3)

        llm_start = time.time()

        if detail_shipment_id:
            # Direct shipment lookup - bypass LLM for speed
            generated_sql = (
                f"SELECT * FROM {settings.SHIPMENT_TABLE_NAME} "
                f"WHERE shipment_number_id = '{detail_shipment_id}'"
            )
        else:
            sql_result = llm.generate_sql(
                user_message=processed_message,
                system_prompt=system_prompt,
                conversation_history=llm_context,
            )
            generated_sql = sql_result.sql

        llm_time_ms = _elapsed_ms(llm_start)

        # =====================================================================
        # STEP 4: SQL Validation (Guardrails)
        # =====================================================================
        validation = validator.validate(generated_sql)

        if not validation.is_valid:
            # =====================================================================
            # STEP 5: SQL Repair (if validation failed)
            # =====================================================================
            logger.warning(
                "SQL validation failed: %s. Attempting repair...",
                validation.error_summary,
            )
            repair_result = llm.repair_sql(
                original_sql=generated_sql,
                error_message=validation.error_summary,
                system_prompt=system_prompt,
                user_message=processed_message,
            )
            generated_sql = repair_result.sql

            # Re-validate repaired SQL
            validation = validator.validate(generated_sql)
            if not validation.is_valid:
                # Give up - log and return error
                error_msg = (
                    "I wasn't able to generate a valid query for your question. "
                    f"Issue: {validation.error_summary}. "
                    "Could you try rephrasing?"
                )
                audit.log_query(
                    user_id=user_id, user_query=user_message, intent=intent.value,
                    sql_generated=generated_sql, sql_validated=False,
                    validation_issues=validation.error_summary,
                    execution_status="blocked",
                    total_time_ms=_elapsed_ms(start_time),
                    conversation_id=server_conversation_key,
                )
                conversations.add_message(
                    conversation_id=server_conversation_key, role="assistant",
                    content=error_msg, intent=intent.value,
                )
                return ChatResponse(
                    status="error", message=error_msg,
                    conversation_id=frontend_conversation_id,
                    execution_time_ms=_elapsed_ms(start_time),
                )

        # Use validated (possibly auto-modified) SQL
        final_sql = validation.sql
        was_repaired = validation.was_modified

        # =====================================================================
        # STEP 6: SQL Execution
        # =====================================================================
        query_result = sql_svc.execute_query(final_sql)

        if query_result.error:
            # Execution failed - try repair once
            logger.warning("SQL execution failed: %s", query_result.error[:100])
            repair_result = llm.repair_sql(
                original_sql=final_sql,
                error_message=query_result.error,
                system_prompt=system_prompt,
                user_message=processed_message,
            )
            repaired_sql = repair_result.sql
            repaired_validation = validator.validate(repaired_sql)

            if repaired_validation.is_valid:
                query_result = sql_svc.execute_query(repaired_validation.sql)
                final_sql = repaired_validation.sql
                was_repaired = True

            if query_result.error:
                error_msg = (
                    "I encountered an issue running the query. "
                    "Could you try rephrasing your question? "
                    f"Technical detail: {query_result.error[:150]}"
                )
                audit.log_query(
                    user_id=user_id, user_query=user_message, intent=intent.value,
                    sql_generated=final_sql, sql_validated=True,
                    execution_status="error", error_message=query_result.error[:500],
                    execution_time_ms=query_result.execution_time_ms,
                    llm_time_ms=llm_time_ms,
                    total_time_ms=_elapsed_ms(start_time),
                    was_repaired=was_repaired, conversation_id=server_conversation_key,
                )
                conversations.add_message(
                    conversation_id=server_conversation_key, role="assistant",
                    content=error_msg, intent=intent.value,
                )
                return ChatResponse(
                    status="error", message=error_msg,
                    conversation_id=frontend_conversation_id,
                    execution_time_ms=_elapsed_ms(start_time),
                )

        # =====================================================================
        # STEP 7: Result Processing & Summarization
        # =====================================================================
        headers = query_result.headers
        rows = query_result.rows
        row_count = query_result.row_count
        total_row_count = query_result.total_row_count

        # Generate summary
        if row_count == 0:
            summary = (
                "No results found matching your query. "
                "Try broadening your search criteria or check for typos in filters."
            )
        elif row_count <= 3:
            # Small result - include data in summary
            sample_dicts = [dict(zip(headers, row)) for row in rows[:5]]
            summary = llm.summarize_results(
                user_message=user_message,
                sql=final_sql,
                row_count=total_row_count,
                sample_rows=sample_dicts,
                headers=headers,
            )
        else:
            # Larger result - brief summary
            sample_dicts = [dict(zip(headers, row)) for row in rows[:5]]
            summary = llm.summarize_results(
                user_message=user_message,
                sql=final_sql,
                row_count=total_row_count,
                sample_rows=sample_dicts,
                headers=headers,
            )

        # =====================================================================
        # STEP 8: CSV Export (for large results - full data async)
        # =====================================================================
        download_key = None
        if total_row_count > _EXPORT_THRESHOLD:
            # Create export immediately with available rows (for instant download)
            download_key = audit.create_export(
                headers=headers,
                rows=rows,
                filename_prefix="shipment_query",
            )
            # If result was truncated (500-row cap hit), launch async full export
            if query_result.truncated:
                thread = threading.Thread(
                    target=_async_full_export,
                    args=(final_sql, sql_svc, audit, download_key),
                    daemon=True,
                )
                thread.start()
                logger.info(f"Launched async full export for key={download_key}")

        # =====================================================================
        # STEP 9: Persist & Audit
        # =====================================================================
        # Update conversation title from first query
        conv_data = conversations.get_conversation(server_conversation_key)
        if conv_data and not conv_data.get("title"):
            title = conversations.generate_title(user_message)
            conversations.update_title(server_conversation_key, title)

        # Store assistant message
        conversations.add_message(
            conversation_id=server_conversation_key,
            role="assistant",
            content=summary,
            sql_generated=final_sql,
            sql_result_summary=summary[:200],
            row_count=total_row_count,
            execution_time_ms=query_result.execution_time_ms,
            intent=intent.value,
        )

        # Audit log
        audit.log_query(
            user_id=user_id, user_query=user_message, intent=intent.value,
            sql_generated=final_sql, sql_validated=True,
            execution_status="success", row_count=total_row_count,
            execution_time_ms=query_result.execution_time_ms,
            llm_time_ms=llm_time_ms,
            total_time_ms=_elapsed_ms(start_time),
            was_repaired=was_repaired, conversation_id=server_conversation_key,
        )

        # =====================================================================
        # STEP 10: Build Response
        # =====================================================================
        is_table = row_count > 0 and len(headers) > 1
        table_data = None
        if is_table:
            # Serialize rows (convert non-serializable types)
            serialized_rows = [
                [_serialize_value(v) for v in row] for row in rows
            ]
            table_data = TableData(headers=headers, rows=serialized_rows)

        return ChatResponse(
            status="success",
            message=summary,
            is_table=is_table,
            table_data=table_data,
            row_count=total_row_count,
            download_key=download_key,
            execution_time_ms=_elapsed_ms(start_time),
            conversation_id=frontend_conversation_id,
        )

    except Exception as e:
        logger.exception("Chat pipeline error: %s", str(e)[:200])
        # Include brief technical detail so issues can be diagnosed from the UI
        tech_detail = str(e)[:150] if str(e) else type(e).__name__
        error_msg = f"I encountered an issue running the query. Could you try rephrasing your question? Technical detail: {tech_detail}"

        # Best-effort audit
        try:
            audit.log_query(
                user_id=user_id, user_query=user_message,
                execution_status="error", error_message=str(e)[:500],
                total_time_ms=_elapsed_ms(start_time),
                conversation_id=server_conversation_key,
            )
        except Exception:
            pass

        return ChatResponse(
            status="error", message=error_msg,
            conversation_id=frontend_conversation_id,
            execution_time_ms=_elapsed_ms(start_time),
        )


# =============================================================================
# HELPERS
# =============================================================================


def _fast_classify(message: str) -> Optional[str]:
    """Fast pattern-match for PURE greetings only. Skips LLM call.

    Returns a greeting category ONLY if the message is purely a greeting
    (short, no query-indicating keywords). Returns None for anything that
    contains a real data question — even if it starts with "hi".

    Examples:
        "hi" → "hello"
        "how are you?" → "casual"
        "hi can you give me shipments from Mexico?" → None (has query content)
        "hey show me delays" → None (has query content)
    """
    lower = message.lower().strip().rstrip("!?.")

    # Never fast-classify long messages
    if len(lower) > 60:
        return None

    # CRITICAL: If message contains any query-indicating keywords, it's NOT
    # a pure greeting — let it go through the full pipeline
    if has_query_intent(message):
        return None

    # Only match very short messages (≤6 words) with no query content
    word_count = len(lower.split())
    if word_count > 6:
        return None

    # Now safe to check greeting patterns
    for category, patterns in _GREETING_PATTERNS.items():
        if any(lower.startswith(p) or lower == p for p in patterns):
            return category
    return None


def _strip_greeting_prefix(message: str) -> str:
    """Strip greeting prefix from messages that contain a real query.

    'hi can you give me shipments from Mexico?' → 'can you give me shipments from Mexico?'
    'hello, show me delays for ADC' → 'show me delays for ADC'
    'hey' → 'hey' (pure greeting, no stripping)

    Only strips if the remainder contains query content (safety check).
    """
    lower = message.lower().strip()
    for prefix in _GREETING_PREFIXES:
        if lower.startswith(prefix):
            remainder = message[len(prefix):].lstrip(", ")
            # Only strip if the remainder is substantial (has query content)
            if len(remainder) > 3 and has_query_intent(remainder):
                return remainder
    # Also handle "hi, can you..." with comma
    comma_match = re.match(r"^(?:hi|hey|hello|yo)\s*[,!]\s*", message, re.IGNORECASE)
    if comma_match:
        remainder = message[comma_match.end():]
        if len(remainder) > 3 and has_query_intent(remainder):
            return remainder
    return message


def _async_full_export(sql: str, sql_svc, audit, download_key: str):
    """Run full SQL query in background thread for CSV export."""
    try:
        result = sql_svc.execute_query(sql, row_limit=100_000)
        if not result.error and result.rows:
            audit.update_export(download_key=download_key, headers=result.headers, rows=result.rows)
            logger.info(f"Async export done: {download_key} ({len(result.rows)} rows)")
    except Exception as e:
        logger.error(f"Async export error: {e}")


def _preprocess_message(message: str) -> str:
    """Apply business rules preprocessing to user message."""
    processed = message
    processed = convert_country_to_iso(processed)
    return processed


def _elapsed_ms(start_time: float) -> int:
    """Calculate elapsed milliseconds since start_time."""
    return int((time.time() - start_time) * 1000)


def _serialize_value(value) -> str:
    """Convert a value to JSON-serializable string."""
    if value is None:
        return None
    if isinstance(value, (int, float, bool)):
        return value
    return str(value)


def _genie_table_to_table_data(td: Optional[dict]) -> Optional[TableData]:
    """Convert a Genie mapper table_data dict to the TableData Pydantic model.

    The Genie response mapper returns table_data as a plain dict
    {"headers": [...], "rows": [[...], ...]}.  This function wraps it
    into the TableData model that ChatResponse expects.

    Returns None for None, empty dicts, or any falsy value so that
    is_table=False responses never produce a spurious empty TableData.
    """
    if not td:
        return None
    return TableData(
        headers=td.get("headers", []),
        rows=td.get("rows", []),
    )
